import Foundation
import XCTest
@testable import AICaddie

/// B4b-2 §6: the iPhone round-identity rule set agrees with the server and the Watch on the shared
/// corpus `Fixtures/round_identity_cases.json` (generated by `tests/test_round_identity_cases.py`).
/// Every valid case is accepted and every invalid case is rejected by
/// ``LiveRoundPackage/validateRoundIdentity(schema:roundLoops:loopKey:holes:)``, the same rules
/// SyncClient applies to server packages and OfflineStore applies to every durable package.
final class RoundIdentityCasesTests: XCTestCase {
    /// The identity fields of one case package; the rest of the package is not part of the rule.
    private struct IdentityCase: Decodable {
        let schema: String
        let roundLoops: [RoundLoop]
        let loopKey: String
        let holes: [LiveRoundPackage.RoundIdentityHole]
    }

    private struct Corpus: Decodable {
        let valid: [String: IdentityCase]
        let invalid: [String: IdentityCase]
    }

    private func corpusURL() throws -> URL {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle(for: RoundIdentityCasesTests.self)
        #endif
        if let nested = bundle.url(
            forResource: "round_identity_cases",
            withExtension: "json",
            subdirectory: "Fixtures"
        ) {
            return nested
        }
        return try XCTUnwrap(
            bundle.url(forResource: "round_identity_cases", withExtension: "json"),
            "round_identity_cases.json must be bundled with the iOS unit tests"
        )
    }

    private func corpus() throws -> Corpus {
        try JSONDecoder().decode(Corpus.self, from: Data(contentsOf: corpusURL()))
    }

    private func validate(_ identity: IdentityCase) throws {
        try LiveRoundPackage.validateRoundIdentity(
            schema: identity.schema,
            roundLoops: identity.roundLoops,
            loopKey: identity.loopKey,
            holes: identity.holes
        )
    }

    func testEveryValidSharedCaseIsAccepted() throws {
        let cases = try corpus().valid
        XCTAssertFalse(cases.isEmpty, "the shared corpus must carry valid cases")
        for name in cases.keys.sorted() {
            let identity = try XCTUnwrap(cases[name])
            XCTAssertNoThrow(try validate(identity), "valid case \(name) must be accepted")
        }
    }

    func testEveryInvalidSharedCaseIsRejected() throws {
        let cases = try corpus().invalid
        XCTAssertFalse(cases.isEmpty, "the shared corpus must carry invalid cases")
        for name in cases.keys.sorted() {
            let identity = try XCTUnwrap(cases[name])
            XCTAssertThrowsError(try validate(identity), "invalid case \(name) must be rejected") { error in
                XCTAssertTrue(error is RoundIdentityError, "invalid case \(name): unexpected \(error)")
            }
        }
    }
}
