import Foundation
import XCTest
import AICaddieDomain
@testable import AICaddieWatch

/// B4b-2 §6: the Watch's decode-time round-identity rules agree with the server and the iPhone on
/// the shared corpus `round_identity_cases.json` (generated by `tests/test_round_identity_cases.py`).
/// Each case is served to ``WatchBackendClient/decodeCoursePackage(_:)`` as package bytes: every
/// valid case decodes, every invalid case is refused before it can be played.
final class WatchRoundIdentityCasesTests: XCTestCase {
    private func makeClient() -> WatchBackendClient {
        WatchBackendClient(baseURL: URL(string: "https://caddie.example")!, adminToken: nil)
    }

    private func corpusURL() throws -> URL {
        if let bundled = Bundle(for: WatchRoundIdentityCasesTests.self)
            .url(forResource: "round_identity_cases", withExtension: "json") {
            return bundled
        }
        // A build that does not bundle the corpus (e.g. SwiftPM) reads it next to this file.
        let adjacent = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("round_identity_cases.json")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: adjacent.path),
            "round_identity_cases.json must be bundled with the Watch unit tests"
        )
        return adjacent
    }

    /// `{name: package bytes}` for one side ("valid" / "invalid") of the corpus, each case
    /// re-encoded on its own exactly as a server response body would carry it.
    private func cases(_ side: String) throws -> [String: Data] {
        let root = try XCTUnwrap(
            JSONSerialization.jsonObject(with: Data(contentsOf: corpusURL())) as? [String: Any]
        )
        let packages = try XCTUnwrap(root[side] as? [String: Any], "corpus side \(side)")
        var encoded: [String: Data] = [:]
        for (name, package) in packages {
            encoded[name] = try JSONSerialization.data(withJSONObject: package)
        }
        return encoded
    }

    func testEveryValidSharedCaseDecodes() throws {
        let client = makeClient()
        let valid = try cases("valid")
        XCTAssertFalse(valid.isEmpty, "the shared corpus must carry valid cases")
        for name in valid.keys.sorted() {
            let data = try XCTUnwrap(valid[name])
            XCTAssertNoThrow(try client.decodeCoursePackage(data), "valid case \(name) must decode")
        }
    }

    func testEveryInvalidSharedCaseIsRefused() throws {
        let client = makeClient()
        let invalid = try cases("invalid")
        XCTAssertFalse(invalid.isEmpty, "the shared corpus must carry invalid cases")
        for name in invalid.keys.sorted() {
            let data = try XCTUnwrap(invalid[name])
            XCTAssertThrowsError(try client.decodeCoursePackage(data), "invalid case \(name) must be refused")
        }
    }
}
