"""legacy_map_user_unique

Revision ID: 0002_legacy_map_user_unique
Revises: 0001_identity
Create Date: 2026-06-27 12:09:03.481108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_legacy_map_user_unique'
down_revision: Union[str, Sequence[str], None] = '0001_identity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legacy_player_map', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_legacy_map_user', ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legacy_player_map', schema=None) as batch_op:
        batch_op.drop_constraint('uq_legacy_map_user', type_='unique')

    # ### end Alembic commands ###
