"""legacy_map_user_unique

Revision ID: 0002_legacy_map_user_unique
Revises: 0001_identity
Create Date: 2026-06-27 12:09:03.481108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_legacy_map_user_unique'
down_revision: Union[str, Sequence[str], None] = '0001_identity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Preflight: adding UNIQUE(user_id) would abort with an opaque IntegrityError if the
    # table already holds duplicate user_id rows. The pre-0002 repo allowed that shape
    # (map_legacy_player keyed only by legacy_player_id; reverse lookup used .first()), so a
    # real DB might contain them. Fail fast with an actionable message instead of a raw
    # constraint-violation traceback.
    bind = op.get_bind()
    dups = bind.execute(
        sa.text(
            "SELECT user_id FROM legacy_player_map "
            "GROUP BY user_id HAVING COUNT(*) > 1"
        )
    ).fetchall()
    if dups:
        offending = ", ".join(str(row[0]) for row in dups)
        raise RuntimeError(
            "Cannot add UNIQUE(legacy_player_map.user_id): duplicate user_id rows exist "
            f"({offending}). Each user must map to at most one legacy player — resolve the "
            "duplicates before upgrading to 0002."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legacy_player_map', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_legacy_map_user', ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legacy_player_map', schema=None) as batch_op:
        batch_op.drop_constraint('uq_legacy_map_user', type_='unique')

    # ### end Alembic commands ###
