#!/usr/bin/env bash
set -euo pipefail

# Build a content-level, deletion-independent inventory of disposable source
# snapshots.  This script is intentionally read-only with respect to the
# snapshots: it only writes its manifest under the persistent data directory.

WORKTREES="${AICADDIE_WORKTREES:-/home/jason/codex-runs/garmin-ai-caddie-p0-watch-20260822/.claude/worktrees}"
OUT_ROOT="${AICADDIE_MANIFEST_ROOT:-/home/jason/garmin-ai-caddie-data/cleanup-manifests}"
STAMP="${AICADDIE_MANIFEST_STAMP:-$(date -u +%Y-%m-%dT%H%M%SZ)}"
OUT="$OUT_ROOT/$STAMP-worktree-audit"

if [[ ! -d "$WORKTREES" ]]; then
  printf 'worktrees_not_found=%s\n' "$WORKTREES" >&2
  exit 2
fi

umask 077
mkdir -p "$OUT/files" "$OUT/links"

{
  printf 'timestamp_utc=%s\n' "$STAMP"
  printf 'host=%s\n' "$(hostname)"
  printf 'user=%s\n' "$(id -un)"
  printf 'worktrees=%s\n' "$WORKTREES"
  printf 'root_disk='; df -hP / | tail -n 1
  printf 'worktrees_disk='; du -sh "$WORKTREES" 2>/dev/null | awk '{print $1}'
  printf 'directory_count=%s\n' "$(find "$WORKTREES" -mindepth 1 -maxdepth 1 -type d | wc -l)"
  printf '\n[exclusions]\n'
  printf '%s\n' '.git' '.venv' 'node_modules' '.build' 'dist' '.codex-tmp'
} > "$OUT/summary.txt"

# Record processes whose current working directory or open descriptor is in a
# snapshot.  It is a guardrail for the later, separate deletion step.
{
  for proc in /proc/[0-9]*; do
    pid="${proc##*/}"
    [[ -r "$proc/cmdline" ]] || continue
    cmdline="$(tr '\0' ' ' < "$proc/cmdline" 2>/dev/null || true)"
    cwd="$(readlink "$proc/cwd" 2>/dev/null || true)"
    case "$cwd" in
      "$WORKTREES"/*) printf 'cwd\t%s\t%s\t%s\n' "$pid" "$cwd" "$cmdline";;
    esac
    for fd in "$proc"/fd/*; do
      link="$(readlink "$fd" 2>/dev/null || true)"
      case "$link" in
        "$WORKTREES"/*)
          printf 'fd\t%s\t%s\t%s\n' "$pid" "$link" "$cmdline"
          break
          ;;
      esac
    done
  done
} > "$OUT/process-use.tsv"

printf 'name\tbytes\tregular_files\tsymlinks\tmtime\tgit_pointer\tmanifest\tmanifest_sha256\n' > "$OUT/worktrees.tsv"

hash_tree() {
  local name="$1" dir="$2" output="$3" record file rel bytes digest
  : > "$output"
  # Hash a whole tree in one process.  The previous per-file invocation made
  # a 79-snapshot audit needlessly expensive on the four-core server.
  while IFS= read -r -d '' record; do
    digest="${record:0:64}"
    file="${record:66}"
    rel="${file#"$dir"/}"
    bytes="$(stat -c '%s' "$file")"
    printf '%s\t%s\t%s\n' "$digest" "$bytes" "$rel" >> "$output"
  done < <(
    find "$dir" -type f \
      -not -path "$dir/.git" -not -path "$dir/.git/*" \
      -not -path "$dir/.venv" -not -path "$dir/.venv/*" \
      -not -path "$dir/node_modules" -not -path "$dir/node_modules/*" \
      -not -path "$dir/.build" -not -path "$dir/.build/*" \
      -not -path "$dir/dist" -not -path "$dir/dist/*" \
      -not -path "$dir/.codex-tmp" -not -path "$dir/.codex-tmp/*" \
      -print0 | sort -z | xargs -0 -r sha256sum --zero
  )
}

for dir in "$WORKTREES"/*; do
  [[ -d "$dir" ]] || continue
  name="${dir##*/}"
  # Snapshot names are generated by Claude and are safe path components.  Keep
  # an explicit fallback so a future unusual name cannot escape the manifest.
  safe_name="${name//[^A-Za-z0-9._+-]/_}"
  manifest="$OUT/files/$safe_name.sha256.tsv"
  links="$OUT/links/$safe_name.tsv"
  hash_tree "$name" "$dir" "$manifest"
  find "$dir" -type l -printf '%P\t%l\n' | sort > "$links"
  bytes="$(du -sk "$dir" | awk '{print $1 * 1024}')"
  regular="$(find "$dir" -type f | wc -l)"
  symlinks="$(find "$dir" -type l | wc -l)"
  mtime="$(stat -c '%y' "$dir")"
  pointer=""
  if [[ -f "$dir/.git" ]]; then
    pointer="$(sed -n '1p' "$dir/.git" | tr '\t' ' ' || true)"
  fi
  manifest_sha="$(sha256sum "$manifest" | awk '{print $1}')"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$bytes" "$regular" "$symlinks" "$mtime" "$pointer" \
    "${manifest#"$OUT"/}" "$manifest_sha" >> "$OUT/worktrees.tsv"
done

# Keep the schema header at the top; sort only data rows.
{ head -n 1 "$OUT/worktrees.tsv"; tail -n +2 "$OUT/worktrees.tsv" | sort; } > "$OUT/worktrees.tsv.sorted"
mv "$OUT/worktrees.tsv.sorted" "$OUT/worktrees.tsv"

# Aggregate content occurrences.  A hash+size appearing in one tree is a
# candidate for unique preservation; it is never deleted by this script.
awk -F '\t' 'FNR == 1 { next } { key=$1 FS $2; trees[key] = trees[key] "," FILENAME; count[key]++ } END { for (key in count) print count[key] FS key FS trees[key] }' \
  "$OUT"/files/*.sha256.tsv | sort -n > "$OUT/content-occurrences.tsv"
awk -F '\t' '$1 == 1 { print }' "$OUT/content-occurrences.tsv" > "$OUT/unique-content-candidates.tsv"

# List paths whose names commonly indicate credentials.  Values are never
# printed; this is a review gate before any archive or deletion operation.
rg -l --hidden --glob '!**/.git/**' --glob '!**/.venv/**' \
  -g '*.env' -g '*.env.*' -g '*token*' -g '*secret*' -g '*credential*' -g '*.pem' -g '*.p12' \
  "$WORKTREES" > "$OUT/sensitive-path-candidates.txt" 2>/dev/null || true

{
  printf 'manifest_root=%s\n' "$OUT"
  printf 'worktree_rows=%s\n' "$(($(wc -l < "$OUT/worktrees.tsv") - 1))"
  printf 'unique_content_rows=%s\n' "$(wc -l < "$OUT/unique-content-candidates.tsv")"
  printf 'process_use_rows=%s\n' "$(wc -l < "$OUT/process-use.tsv")"
  printf 'sensitive_path_rows=%s\n' "$(wc -l < "$OUT/sensitive-path-candidates.txt")"
} >> "$OUT/summary.txt"

find "$OUT" -type f -not -name manifest.sha256 -print0 | sort -z |
  xargs -0 -r sha256sum > "$OUT/manifest.sha256"
printf '%s\n' "$OUT"
