#!/usr/bin/env bash
# Block until one CI/release run or one PR-feedback event has a conclusion.
#
# The command is intended to run on the homeserver. It owns the polling,
# writes detailed output to a durable log, and prints exactly one summary line
# when it returns. This keeps the Codex control thread from repeatedly
# querying GitHub or the homeserver while a run is in flight.
set -u

REPO="${WAIT_REPO:-jasonhorga/garmin-ai-caddie}"
DATA_ROOT="${WAIT_DATA_ROOT:-/home/jason/garmin-ai-caddie-data/operations/blocking-waits}"
EVENT_FILE="${WAIT_EVENT_FILE:-/home/jason/garmin-ai-caddie-data/operations/pr-feedback-monitor/events.jsonl}"
POLL_SECONDS="${WAIT_POLL_SECONDS:-15}"
TIMEOUT_SECONDS="${WAIT_TIMEOUT_SECONDS:-0}"
SELF_COMMIT_LOGIN="${WAIT_SELF_COMMIT_LOGIN:-jasonhorga}"
SELF_COMMIT_EMAIL="${WAIT_SELF_COMMIT_EMAIL:-jasonhe@gmail.com}"
# Every agent pushes under the same GitHub identity, so provenance has to come
# from the commit message: Codex's trailer marks its own commits and Claude's
# trailer marks Claude's. Identity alone only covers unmarked bookkeeping.
CODEX_COMMIT_MARKER="${WAIT_CODEX_COMMIT_MARKER:-Generated-by: Codex|_Generated by Codex_}"
OTHER_AGENT_COMMIT_MARKER="${WAIT_OTHER_AGENT_COMMIT_MARKER:-Co-Authored-By: Claude|Generated with \\[Claude Code\\]|Claude-Session:}"
MODE=""
RUN_ID=""
PR_NUMBER=""
LOG_FILE=""
EVENT_TAIL_PID=""

usage() {
  cat <<'USAGE'
Usage:
  ops/wait_for_conclusion.sh --run RUN_ID [options]
  ops/wait_for_conclusion.sh --release RUN_ID [options]
  ops/wait_for_conclusion.sh --pr PR_NUMBER [options]
  ops/wait_for_conclusion.sh --feedback [options]

Modes:
  --run ID       Block on a GitHub Actions run.
  --release ID   Alias for --run, labelled as a release wait.
  --pr NUMBER    Block on the next event for a PR in the existing monitor
                 JSONL stream (comments, reviews, commits, heads, or CI).
  --feedback     Block on the next event for any PR in that stream.

Options:
  --repo OWNER/REPO       Repository (default: $WAIT_REPO or this project).
  --data-root PATH        Durable log directory (default: $WAIT_DATA_ROOT).
  WAIT_LATEST_RESULT_FILE Environment override for the atomically replaced
                          one-line latest-result file (default: data-root).
  --event-file PATH       PR monitor JSONL stream (default: $WAIT_EVENT_FILE).
  --poll-seconds N        Internal wait/read interval (default: 15).
  --timeout-seconds N     0 means wait forever (default: 0).
  --log PATH              Exact log path; otherwise one is created in data-root.
  WAIT_SELF_COMMIT_LOGIN / WAIT_SELF_COMMIT_EMAIL identify Codex's commit
                         identity for ignoring self-generated main-branch runs.
  WAIT_CODEX_COMMIT_MARKER / WAIT_OTHER_AGENT_COMMIT_MARKER
                          Message patterns that mark Codex's own commits and
                          other agents' commits (default: the attribution
                          trailers required by AGENTS.md).
  WAIT_CURSOR_FILE        Where --feedback remembers the last consumed event
                          line (default: data-root/feedback-cursor), so a
                          restarted waiter resumes there instead of at EOF.
  -h, --help              Show this help.

Output is one line:
  status=... conclusion=... failed_jobs=... log=/absolute/path/to/log
USAGE
}

is_uint() {
  [[ "${1:-}" =~ ^[0-9]+$ ]]
}

die_usage() {
  printf 'error: %s\n' "$1" >&2
  usage >&2
  exit 2
}

while (($#)); do
  case "$1" in
    --run)
      (($# >= 2)) || die_usage "--run needs a run id"
      MODE="ci"
      RUN_ID="$2"
      shift 2
      ;;
    --release)
      (($# >= 2)) || die_usage "--release needs a run id"
      MODE="release"
      RUN_ID="$2"
      shift 2
      ;;
    --pr)
      (($# >= 2)) || die_usage "--pr needs a pull request number"
      MODE="pr"
      PR_NUMBER="$2"
      shift 2
      ;;
    --feedback|--all-prs)
      MODE="feedback"
      shift
      ;;
    --repo)
      (($# >= 2)) || die_usage "--repo needs OWNER/REPO"
      REPO="$2"
      shift 2
      ;;
    --data-root)
      (($# >= 2)) || die_usage "--data-root needs a path"
      DATA_ROOT="$2"
      shift 2
      ;;
    --event-file)
      (($# >= 2)) || die_usage "--event-file needs a path"
      EVENT_FILE="$2"
      shift 2
      ;;
    --poll-seconds)
      (($# >= 2)) || die_usage "--poll-seconds needs an integer"
      POLL_SECONDS="$2"
      shift 2
      ;;
    --timeout-seconds)
      (($# >= 2)) || die_usage "--timeout-seconds needs an integer"
      TIMEOUT_SECONDS="$2"
      shift 2
      ;;
    --log)
      (($# >= 2)) || die_usage "--log needs a path"
      LOG_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die_usage "unknown argument: $1"
      ;;
  esac
done

[[ -n "$MODE" ]] || die_usage "one of --run, --release, or --pr is required"
if [[ "$MODE" == "pr" ]]; then
  is_uint "$PR_NUMBER" || die_usage "PR number must be an integer"
elif [[ "$MODE" != "feedback" ]]; then
  is_uint "$RUN_ID" || die_usage "run id must be an integer"
fi
is_uint "$POLL_SECONDS" || die_usage "poll interval must be an integer"
is_uint "$TIMEOUT_SECONDS" || die_usage "timeout must be an integer"
(( POLL_SECONDS > 0 )) || die_usage "poll interval must be greater than zero"

umask 077
mkdir -p "$DATA_ROOT"
LATEST_RESULT_FILE="${WAIT_LATEST_RESULT_FILE:-$DATA_ROOT/latest-result.txt}"
CURSOR_FILE="${WAIT_CURSOR_FILE:-$DATA_ROOT/feedback-cursor}"
latest_result_parent="${LATEST_RESULT_FILE%/*}"
[[ "$latest_result_parent" != "$LATEST_RESULT_FILE" ]] && mkdir -p "$latest_result_parent"
if [[ -z "$LOG_FILE" ]]; then
  subject="${MODE}-${RUN_ID:-pr-${PR_NUMBER}}"
  subject="${subject//[^A-Za-z0-9_.-]/_}"
  LOG_FILE="$DATA_ROOT/wait-${subject}-$(date -u +%Y%m%dT%H%M%SZ)-$$.log"
else
  log_parent="${LOG_FILE%/*}"
  [[ "$log_parent" != "$LOG_FILE" ]] && mkdir -p "$log_parent"
fi
touch "$LOG_FILE"

log() {
  printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >>"$LOG_FILE"
}

deadline=""
if (( TIMEOUT_SECONDS > 0 )); then
  deadline=$(( $(date +%s) + TIMEOUT_SECONDS ))
fi

timed_out() {
  [[ -n "$deadline" ]] && (( $(date +%s) >= deadline ))
}

# Remember the last event line this --feedback waiter consumed, so the next
# waiter resumes from there. Written atomically; one line, the line number.
advance_cursor() {
  [[ "$MODE" == "feedback" ]] || return 0
  local cursor_tmp="${CURSOR_FILE}.tmp.$$"
  printf '%s\n' "$1" >"$cursor_tmp" && mv -f "$cursor_tmp" "$CURSOR_FILE"
}

finish() {
  local status="$1" conclusion="$2" failed_jobs="$3" exit_code="${4:-0}"
  if [[ "$MODE" == "feedback" && -n "${line_no:-}" ]] && (( line_no > 0 )); then
    advance_cursor "$line_no"
  fi
  # The only normal stdout emitted by this command is this summary line. Keep
  # the same line in a durable, atomically replaced file for tmux callers.
  local summary="status=$status conclusion=$conclusion failed_jobs=$failed_jobs log=$LOG_FILE"
  local result_tmp="${LATEST_RESULT_FILE}.tmp.$$"
  printf '%s\n' "$summary" >"$result_tmp"
  mv -f "$result_tmp" "$LATEST_RESULT_FILE"
  printf '%s\n' "$summary"
  exit "$exit_code"
}

cleanup() {
  if [[ -n "$EVENT_TAIL_PID" ]] && kill -0 "$EVENT_TAIL_PID" 2>/dev/null; then
    kill "$EVENT_TAIL_PID" 2>/dev/null || true
    wait "$EVENT_TAIL_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

summarize_run() {
  local summarize_run_id="$1"
  # Explicit --run/--release waits are authoritative requests for that exact
  # run, even when the commit has Codex's identity.  Self-generated filtering
  # is only for broad PR-feedback/event waits, where a docs-only main push
  # must not wake the loop or reset the quiet-period clock.
  local ignore_self_generated="${2:-1}"
  log "reading terminal run summary run=$summarize_run_id"
  run_json="$LOG_FILE.run-${summarize_run_id}.json"
  set +e
  gh run view "$summarize_run_id" --repo "$REPO" --json status,conclusion,jobs,url,headBranch,headSha,workflowName,event >"$run_json" 2>>"$LOG_FILE"
  view_rc=$?
  if (( view_rc != 0 )) || ! jq -e . "$run_json" >/dev/null 2>>"$LOG_FILE"; then
    log "unable to read final run state (gh run view exit=$view_rc)"
    finish error gh_error unknown 1
  fi

  status="$(jq -r '.status // "unknown"' "$run_json" 2>>"$LOG_FILE")"
  conclusion="$(jq -r '.conclusion // "unknown"' "$run_json" 2>>"$LOG_FILE")"

  if [[ "$ignore_self_generated" == "1" ]] && run_is_self_generated "$run_json"; then
    log "ignoring self-generated CI run=$summarize_run_id branch=$(jq -r '.headBranch // empty' "$run_json") head=$(jq -r '.headSha // empty' "$run_json")"
    rm -f "$run_json"
    return 42
  fi

  failed_jobs="$(jq -r '
    if (.jobs | type) != "array" then "unknown"
    else
      [.jobs[] | select((.conclusion // "") != "" and
        (.conclusion // "") != "success" and
        (.conclusion // "") != "skipped" and
        (.conclusion // "") != "neutral") | .name]
      | unique | if length == 0 then "none" else join(",") end
    end
  ' "$run_json" 2>>"$LOG_FILE")"
  [[ -n "$failed_jobs" ]] || failed_jobs="unknown"

  {
    printf '\n--- final run JSON ---\n'
    cat "$run_json"
    printf '\n--- complete run log ---\n'
  } >>"$LOG_FILE"
  set +e
  gh run view "$summarize_run_id" --repo "$REPO" --log >>"$LOG_FILE" 2>&1
  log_rc=$?
  log "complete run log exit=$log_rc"
  rm -f "$run_json"

  if [[ "$status" == "completed" && "$conclusion" == "success" ]]; then
    finish "$status" "$conclusion" "$failed_jobs" 0
  fi
  finish "$status" "$conclusion" "$failed_jobs" 1
}

commit_is_self_generated() {
  local commit_sha="$1"
  # marker_only=1: only Codex's explicit trailer counts. Used off main, where an
  # unmarked docs-only commit may be anyone's PR and must still wake the loop.
  local marker_only="${2:-0}"
  local commit_json="$LOG_FILE.commit-${commit_sha}.json"
  [[ "$commit_sha" =~ ^[0-9a-fA-F]{7,64}$ ]] || return 1
  if ! gh api "repos/$REPO/commits/$commit_sha" >"$commit_json" 2>>"$LOG_FILE"; then
    log "unable to inspect commit for self-run filtering sha=$commit_sha"
    rm -f "$commit_json"
    return 1
  fi
  # Self-generated means: carries Codex's own trailer, or is unmarked, under
  # the shared identity, and touches only docs/state bookkeeping. A commit
  # carrying another agent's trailer is never self-generated, whatever its
  # files: the shared GitHub account cannot tell the agents apart by itself.
  jq -e --arg login "$SELF_COMMIT_LOGIN" --arg email "$SELF_COMMIT_EMAIL" \
    --arg codex "$CODEX_COMMIT_MARKER" --arg other "$OTHER_AGENT_COMMIT_MARKER" \
    --argjson marker_only "$marker_only" '
    (.commit.message // "") as $message
    | ($message | test($codex; "i")) as $codex_marked
    | ($message | test($other; "i")) as $other_marked
    | ((.author.login // "") == $login or
        (.committer.login // "") == $login or
        (.commit.author.email // "") == $email or
        (.commit.committer.email // "") == $email) as $shared_identity
    | ((.files // []) | length > 0) as $has_files
    | ((.files // []) | all(.[]?.filename // "";
        . == "AGENTS.md" or startswith("docs/"))) as $bookkeeping_only
    | ($other_marked | not) and
      ($codex_marked or
        ($marker_only == 0 and $shared_identity and $has_files and $bookkeeping_only))
  ' "$commit_json" >/dev/null 2>>"$LOG_FILE"
  local result=$?
  rm -f "$commit_json"
  return "$result"
}

# Manual release and Apple operations have their own terminal outcomes, even
# when they run on a Codex merge or bookkeeping head. Verify the real Actions
# metadata; an event's head or claimed workflow name is not enough. Keep this
# allow-list narrow so manual Native CI still obeys self-run suppression.
run_is_manual_release_operation() {
  jq -e '
    .event == "workflow_dispatch" and
    (.workflowName == "iOS TestFlight (CD)" or
     .workflowName == "iOS TestFlight Testers" or
     .workflowName == "iOS TestFlight Artifact Diagnostics")
  ' "$1" >/dev/null 2>>"$LOG_FILE"
}

run_is_self_generated() {
  local run_json="$1"
  local head_branch head_sha
  if run_is_manual_release_operation "$run_json"; then
    log "keeping manual release/Apple outcome workflow=$(jq -r '.workflowName' "$run_json")"
    return 1
  fi
  head_branch="$(jq -r '.headBranch // empty' "$run_json" 2>>"$LOG_FILE")"
  head_sha="$(jq -r '.headSha // empty' "$run_json" 2>>"$LOG_FILE")"
  ci_head_is_self_generated "$head_branch" "$head_sha"
}

# Codex's own CI on any branch: main keeps the unmarked docs/state bookkeeping
# rule; every other branch (internal release branches such as
# codex/internal-release-*, or a Codex fix pushed to a PR) needs the trailer.
ci_head_is_self_generated() {
  local head_branch="$1" head_sha="$2"
  [[ -n "$head_sha" ]] || return 1
  if [[ "$head_branch" == "main" ]]; then
    commit_is_self_generated "$head_sha"
  else
    commit_is_self_generated "$head_sha" 1
  fi
}

# A PR check summary (`ci_changed`) carries no head of its own, only each check's
# Actions link. It is self-generated only when every check links to a run whose
# head is self-generated; a check without an Actions run link, a run that cannot
# be read, or any other agent's head keeps the event (PR #388 review).
checks_event_is_self_generated() {
  local event="$1" run_ids run_id run_json self_generated_rc
  run_ids="$(jq -r '
    [.checks[]? | ((.link // .detailsUrl // .url // "")
      | (capture("/actions/runs/(?<id>[0-9]+)") | .id) // "missing")]
    | unique | .[]
  ' <<<"$event" 2>>"$LOG_FILE")"
  [[ -n "$run_ids" ]] || return 1
  while IFS= read -r run_id; do
    [[ "$run_id" =~ ^[0-9]+$ ]] || return 1
    run_json="$LOG_FILE.checks-run-${run_id}.json"
    if ! gh run view "$run_id" --repo "$REPO" --json headBranch,headSha,workflowName,event >"$run_json" 2>>"$LOG_FILE"; then
      log "unable to read check run for self-run filtering run=$run_id"
      rm -f "$run_json"
      return 1
    fi
    run_is_self_generated "$run_json"
    self_generated_rc=$?
    rm -f "$run_json"
    (( self_generated_rc == 0 )) || return 1
  done <<<"$run_ids"
  return 0
}

wait_for_run() {
  log "waiting mode=$MODE repo=$REPO run=$RUN_ID"
  set +e
  gh run watch "$RUN_ID" --repo "$REPO" --interval "$POLL_SECONDS" --exit-status >>"$LOG_FILE" 2>&1
  watch_rc=$?
  log "gh run watch exit=$watch_rc"
  summarize_run "$RUN_ID" 0
  summary_rc=$?
  if (( summary_rc == 42 )); then
    finish ignored self_generated_main none 0
  fi
  return "$summary_rc"
}

event_matches_pr() {
  local event="$1"
  if [[ "$MODE" == "feedback" ]]; then
    jq -e '((.kind? // "") | length > 0)' <<<"$event" >/dev/null 2>>"$LOG_FILE"
    return
  fi
  jq -e --argjson pr "$PR_NUMBER" '
    ((.pr? == $pr) or
      (((.pullRequests? // []) |
        map(if type == "number" then . else (tonumber? // -1) end) |
        index($pr)) != null)) and
    ((.kind? // "") | length > 0)
  ' <<<"$event" >/dev/null 2>>"$LOG_FILE"
}

event_is_conclusive() {
  local event="$1"
  jq -e '
    (.kind // "") as $kind |
    if ($kind == "ci_run_added" or $kind == "ci_run_changed") then
      (((.conclusion // "") | length) > 0 or (.status // "") == "completed")
    elif $kind == "ci_changed" then
      ((.checks // []) | length) > 0 and
      all(.checks[]?;
        ((.state // "") | ascii_upcase) as $state |
        ($state != "IN_PROGRESS" and $state != "QUEUED" and
         $state != "PENDING" and $state != "WAITING" and
         $state != "EXPECTED")
      )
    else
      true
    end
  ' <<<"$event" >/dev/null 2>>"$LOG_FILE"
}

wait_for_pr_event() {
  event_parent="${EVENT_FILE%/*}"
  [[ "$event_parent" == "$EVENT_FILE" ]] && event_parent="."
  mkdir -p "$event_parent"
  touch "$EVENT_FILE"
  total_lines=$(wc -l <"$EVENT_FILE")
  start_line=$(( total_lines + 1 ))
  cursor_source="eof"
  # --feedback resumes from the last consumed line, so events appended while
  # no waiter was running (restart, lost SSH session) are still delivered.
  # --pr keeps starting at EOF: a shared cursor would skip other PRs' events.
  if [[ "$MODE" == "feedback" && -r "$CURSOR_FILE" ]]; then
    saved_cursor="$(head -n 1 "$CURSOR_FILE" 2>/dev/null | tr -cd '0-9')"
    if is_uint "$saved_cursor" && (( saved_cursor < total_lines )); then
      start_line=$(( saved_cursor + 1 ))
      cursor_source="cursor"
    fi
  fi
  line_no=$(( start_line - 1 ))
  log "waiting mode=$MODE repo=$REPO pr=${PR_NUMBER:-all} event_file=$EVENT_FILE start_line=$start_line (${cursor_source}; file has $total_lines lines)"

  # The existing monitor owns GitHub polling and appends deduplicated events.
  # This waiter only follows that durable stream, so it does not create a
  # second monitor or duplicate API traffic.
  coproc EVENT_TAIL { exec tail -n +"$start_line" -F "$EVENT_FILE" 2>>"$LOG_FILE"; }
  EVENT_TAIL_PID="$EVENT_TAIL_PID"
  event_fd="${EVENT_TAIL[0]}"
  while :; do
    if timed_out; then
      log "timeout waiting for PR event"
      finish timeout timeout none 124
    fi
    if IFS= read -r -t "$POLL_SECONDS" -u "$event_fd" event_line; then
      line_no=$(( line_no + 1 ))
      printf '%s\n' "$event_line" >>"$LOG_FILE"
      if event_matches_pr "$event_line" && event_is_conclusive "$event_line"; then
        event_kind="$(jq -r '.kind // "pr_feedback"' <<<"$event_line" 2>>"$LOG_FILE")"
        event_pr="$(jq -r 'if .pr? then (.pr|tostring) elif (.pullRequests? // []) | length > 0 then (.pullRequests[0]|tostring) else "all" end' <<<"$event_line" 2>>"$LOG_FILE")"
        log "matched PR event kind=$event_kind"
        event_run_id="$(jq -r '.runId // empty' <<<"$event_line" 2>>"$LOG_FILE")"
        if [[ "$event_kind" == "ci_run_added" || "$event_kind" == "ci_run_changed" ]] && [[ -n "$event_run_id" ]]; then
          event_head_branch="$(jq -r '.headBranch // empty' <<<"$event_line" 2>>"$LOG_FILE")"
          event_head_sha="$(jq -r '.headSha // empty' <<<"$event_line" 2>>"$LOG_FILE")"
          # A terminal Actions event is a run conclusion. Reuse the same
          # summary path as --run so failed job names and the full run log are
          # available in the one-line result. Filtering uses this actual run's
          # workflow/event metadata, not just the stream's commit provenance.
          summarize_run "$event_run_id"
          if (( $? == 42 )); then
            # The final run state named a self-generated head the event did not.
            log "ignored self-generated CI event run=$event_run_id branch=$event_head_branch head=$event_head_sha"
            advance_cursor "$line_no"
            continue
          fi
        elif [[ "$event_kind" == "ci_changed" ]]; then
          if checks_event_is_self_generated "$event_line"; then
            log "ignored self-generated check summary pr=$event_pr"
            advance_cursor "$line_no"
            continue
          fi
          event_failed_jobs="$(jq -r '
            [.checks[]? | select(((.state // "") | ascii_upcase) as $state |
              ($state != "SUCCESS" and $state != "SKIPPED" and $state != "NEUTRAL")) | .name]
            | unique | if length == 0 then "none" else join(",") end
          ' <<<"$event_line" 2>>"$LOG_FILE")"
          [[ -n "$event_failed_jobs" ]] || event_failed_jobs="unknown"
          finish completed ci_checks_terminal "$event_failed_jobs" 0
        else
          finish observed "pr_feedback:${event_kind}:pr${event_pr}" none 0
        fi
      else
        advance_cursor "$line_no"
      fi
    elif ! kill -0 "$EVENT_TAIL_PID" 2>/dev/null; then
      log "event stream exited before a matching event"
      finish error event_stream_closed unknown 1
    fi
  done
}

if [[ "$MODE" == "pr" || "$MODE" == "feedback" ]]; then
  wait_for_pr_event
else
  wait_for_run
fi
